### Get Start with Python

In [1]:
#the basic function
print("Hello World")

Hello World


In [2]:
dir(print)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

#### Defining a variable with `"Complex Datatype"`

In [3]:
# crearting a variable to store some data
c=1+2j

In [4]:
#fetching the imaginary part of the complex number
c.imag

2.0

#### Checking the `"Datatype"` of the variable

In [5]:
type(c)

complex

#### Delete the Varible from the Memory

In [6]:
del (c)

#### After deleting, try to access the Variable 

In [7]:
print(c)

NameError: name 'c' is not defined

$a=b+c$

#### Checking the all variable present in the `"Memory"`

In [8]:
%whos

Interactive namespace is empty.


#### defining multiple variables at a time

In [9]:
b,c,d,e,f=1,14,-34,45.2,10

#### Checking the all variable present in the `"Memory"`

In [10]:
%whos

Variable   Type     Data/Info
-----------------------------
b          int      1
c          int      14
d          int      -34
e          float    45.2
f          int      10


In [11]:
x=90

In [12]:
%whos

Variable   Type     Data/Info
-----------------------------
b          int      1
c          int      14
d          int      -34
e          float    45.2
f          int      10
x          int      90


In [13]:
#finding the function can be use on List
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [14]:
#defining a String
s="How are you buddy"

In [15]:
s

'How are you buddy'

In [16]:
print(type(s))

<class 'str'>


In [17]:
type(s)

str

In [18]:
a="Sandeep"

In [19]:
a

'Sandeep'

In [20]:
_

'Sandeep'

In [21]:
b="New"

In [22]:
b

'New'

In [23]:
_

'New'

In [24]:
%whos

Variable   Type     Data/Info
-----------------------------
a          str      Sandeep
b          str      New
c          int      14
d          int      -34
e          float    45.2
f          int      10
s          str      How are you buddy
x          int      90


In [25]:
'a'>'A'

True

In [26]:
2!=3

True

In [27]:
not True and True and True

False

In [28]:
print(round(7.5))

8


In [29]:
divmod(24,5)

(4, 4)

In [30]:
divmod(2,1)

(2, 0)

In [31]:
isinstance(1,int)

True

In [32]:
pow(2,5)

32

In [33]:
pow(2,4,3)

1

In [34]:
help(input)

Help on method raw_input in module ipykernel.kernelbase:

raw_input(prompt='') method of ipykernel.ipkernel.IPythonKernel instance
    Forward raw_input to frontends
    
    Raises
    ------
    StdinNotImplementedError if active frontend doesn't support stdin.



In [35]:
l=[]
for i in range(10):
    print(i+1)
    l.append(i**2)
print(l)

1
2
3
4
5
6
7
8
9
10
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [36]:
import numpy as np
"""Importing numpy for Numerical Analysis
"""

'Importing numpy for Numerical Analysis\n'

In [37]:
np?

In [38]:
len??

In [39]:
import sys

In [40]:
s="Sandeep"
a="Kumar"

In [41]:
print(type(a))

<class 'str'>


In [42]:
type(s)

str

In [43]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,43,4,5])

In [44]:
np.intersect1d(a,b)

array([1, 2, 4, 5])

In [45]:
print(type(a))

<class 'numpy.ndarray'>


In [46]:
print(type(b))

<class 'numpy.ndarray'>


In [47]:
a.dtype

dtype('int32')

In [48]:
print(a.ndim)

1


In [49]:
print(b.ndim)

1


In [50]:
print(b.shape[0])

5


In [51]:
c=np.array([[[1,2,3],[4,5,0],12,6,7]])

C:\Users\sande\AppData\Local\Temp\ipykernel_2712\340799500.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[[1,2,3],[4,5,0],12,6,7]])


In [52]:
c.ndim

2

In [53]:
c[0,1]

[4, 5, 0]

In [54]:
a=2
b=3
c=5

In [55]:
first=a
second=b
third=c

In [56]:
dir(a)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [57]:
id(a)

1849327315280

In [58]:
a="Sandeep"

In [59]:
id(a)

1849431503536

In [60]:
x=1212431.315341

In [61]:
round(x)

1212431

In [62]:
round(x,4)

1212431.3153

In [63]:
10+2*3

16

In [64]:
(10+2)*3

36

In [65]:
6-5.7

0.2999999999999998

In [66]:
round(6-5.7,2)

0.3

In [67]:
name="Sandeep Kumar"

In [68]:
name[1]

'a'

In [69]:
name[7]

' '

In [70]:
name[3:11]

'deep Kum'

In [71]:
name[::]

'Sandeep Kumar'

In [72]:
name[0:]

'Sandeep Kumar'

In [73]:
address='''Jaipur, Rajasthan'''

In [74]:
address

'Jaipur, Rajasthan'

In [75]:
name1="Sandeep"
name2="Vivek"
name3="Shyam"
names=[name1,name2,name3]

In [76]:
names

['Sandeep', 'Vivek', 'Shyam']

In [77]:
names.append("Pandey")

In [78]:
names

['Sandeep', 'Vivek', 'Shyam', 'Pandey']

In [79]:
names.insert(1,"Anuj")

In [80]:
names

['Sandeep', 'Anuj', 'Vivek', 'Shyam', 'Pandey']

In [81]:
sid=[96674,90161,100365,99695,90765]

In [82]:
details=names+sid

In [83]:
details

['Sandeep',
 'Anuj',
 'Vivek',
 'Shyam',
 'Pandey',
 96674,
 90161,
 100365,
 99695,
 90765]

In [84]:
len(details)

10

In [85]:
"Sandeep" in details

True

In [86]:
"Kuldeep" in details

False

In [87]:
base=10
height=5
area=1/2*(base*height)

In [88]:
area

25.0

In [89]:
expense=[12,1224,14,1234,14,134,314,112]
total=0
for i in expense:
    total+=i
print(total)

3058


In [90]:
for i in expense:
    print("expense is: ",i)

expense is:  12
expense is:  1224
expense is:  14
expense is:  1234
expense is:  14
expense is:  134
expense is:  314
expense is:  112


In [91]:
for i in range(0,11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [92]:
for i in range(len(expense)):
    print('Month:',(i+1),"Expense:",expense[i])

Month: 1 Expense: 12
Month: 2 Expense: 1224
Month: 3 Expense: 14
Month: 4 Expense: 1234
Month: 5 Expense: 14
Month: 6 Expense: 134
Month: 7 Expense: 314
Month: 8 Expense: 112


In [93]:
for i in range(1,50):
    if i%2==0 and i%3==0:
        print(f"The number {i} is divisible by 2 and 3 both")
    if i%3==0 and i%5==0:
        print(f"The number {i} is divisible by 3 and 5 both")
    else:
        print(f"The number is {i}")

The number is 1
The number is 2
The number is 3
The number is 4
The number is 5
The number 6 is divisible by 2 and 3 both
The number is 6
The number is 7
The number is 8
The number is 9
The number is 10
The number is 11
The number 12 is divisible by 2 and 3 both
The number is 12
The number is 13
The number is 14
The number 15 is divisible by 3 and 5 both
The number is 16
The number is 17
The number 18 is divisible by 2 and 3 both
The number is 18
The number is 19
The number is 20
The number is 21
The number is 22
The number is 23
The number 24 is divisible by 2 and 3 both
The number is 24
The number is 25
The number is 26
The number is 27
The number is 28
The number is 29
The number 30 is divisible by 2 and 3 both
The number 30 is divisible by 3 and 5 both
The number is 31
The number is 32
The number is 33
The number is 34
The number is 35
The number 36 is divisible by 2 and 3 both
The number is 36
The number is 37
The number is 38
The number is 39
The number is 40
The number is 41
The

In [94]:
!pip install numpy

In [95]:
import numpy as np

In [96]:
np.array([1,2,3])

array([1, 2, 3])

In [97]:
np.array([1,2,3.7],dtype=int)

array([1, 2, 3])

In [98]:
np.array([1,2,3.7],dtype=float)

array([1. , 2. , 3.7])

In [99]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
np.full((2,2),"Sandeep")

array([['Sandeep', 'Sandeep'],
       ['Sandeep', 'Sandeep']], dtype='<U7')

In [101]:
import numpy as np
zero_d=np.array(3)

In [102]:
zero_d.ndim # work as a 0 dimensional vector

0

##### Creating a `Zero Matrix` with defining their `Dimension`

In [103]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

##### Creating `One-dimensional` array with `1`

In [104]:
np.ones((7),dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

##### Creating an `Identity` with defining the `Data Type`

In [105]:
np.eye((4),dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [107]:
number=input("First Number") #23
number2=input("Second Number") #27
print(number+number2)

First Number45
Second Number12
4512


##### Creating an `identity` Matrix

In [108]:
import numpy as np
np.eye((4),dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### Creating a matrix with all `Zero Valued Element`

In [109]:
mat=np.zeros((3,3),dtype=float)

In [110]:
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### Returning the `Dimension` of the  Matrix

In [111]:
np.ndim(mat)

2

In [112]:
np.abs(23.2432)

23.2432

##### Returning the `Absolute Value`

In [113]:
np.absolute(23.2432)

23.2432

##### Adding two element

In [114]:
np.add(234,23)

257

##### Calculating the `max` element in a  List

In [115]:
np.amax([12,14,1234])

1234

##### Calculating `average` of List

In [116]:
np.average([123,123,41234,124,1234,1234,231])

6329.0

In [117]:
d={"Sandeep":96674,"Pandey":90765,"Vivek":100365}

In [118]:
d

{'Sandeep': 96674, 'Pandey': 90765, 'Vivek': 100365}

In [119]:
d.items()

dict_items([('Sandeep', 96674), ('Pandey', 90765), ('Vivek', 100365)])

In [120]:
d['Sandeep']

96674

In [121]:
d['Shyam']=99695

In [122]:
d

{'Sandeep': 96674, 'Pandey': 90765, 'Vivek': 100365, 'Shyam': 99695}

In [123]:
del d["Vivek"]

In [124]:
d

{'Sandeep': 96674, 'Pandey': 90765, 'Shyam': 99695}

In [125]:
for key in d:
    print("key:",key,"Value:",d[key])

key: Sandeep Value: 96674
key: Pandey Value: 90765
key: Shyam Value: 99695


In [126]:
for k,v in d.items():
    print('Key:',key,"Value:",d[key])

Key: Shyam Value: 99695
Key: Shyam Value: 99695
Key: Shyam Value: 99695


In [127]:
"Sandeep"in d

True

In [128]:
point=(1,2,34,4,1)

In [129]:
point[1]

2

In [130]:
id(point[0])

1849327315248

In [131]:
id(point[4])

1849327315248

In [132]:
id(point[3])

1849327315344

In [133]:
import math

In [134]:
math.sqrt(2)

1.4142135623730951

In [135]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [136]:
import calendar

In [137]:
cal=calendar.month(2016,1)

In [138]:
cal

'    January 2016\nMo Tu We Th Fr Sa Su\n             1  2  3\n 4  5  6  7  8  9 10\n11 12 13 14 15 16 17\n18 19 20 21 22 23 24\n25 26 27 28 29 30 31\n'

In [139]:
dir(calendar)

['Calendar',
 'EPOCH',
 'FRIDAY',
 'February',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'January',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MONDAY',
 'SATURDAY',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_monthlen',
 '_nextmonth',
 '_prevmonth',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthrange',
 'prcal',
 'prmonth',
 'prweek',
 'repeat',
 'setfirstweekday',
 'sys',
 'timegm',
 'week',
 'weekday',
 'weekheader']

In [140]:
book={}
book["Sandeep"]={
    'name':"Sandeep",
    'SID':96674,
    'Course':"B.Tech"
}
book["Pandey"]={
    'name':"Pandey",
    'SID':90765,
    'Course':"B.Tech"
}
book["Vivek"]={
    'name':"Vivek",
    'SID':100365,
    'Course':"B.Tech"
}
book["Shyam"]={
    'name':"Shyam",
    'SID':99695,
    'Course':"B.Tech"
}
book["Ujjawal"]={
    'name':"Ujjawal",
    'SID':100087,
    'Course':"B.Tech"
}
book["Rahul"]={
    'name':"Rahul",
    'SID':90163,
    'Course':"B.Tech"
}
book["Anuj"]={
    'name':"Anuj",
    'SID':90161,
    'Course':"B.Tech"
}

In [141]:
import json

In [142]:
s=json.dumps(book)

In [143]:
s

'{"Sandeep": {"name": "Sandeep", "SID": 96674, "Course": "B.Tech"}, "Pandey": {"name": "Pandey", "SID": 90765, "Course": "B.Tech"}, "Vivek": {"name": "Vivek", "SID": 100365, "Course": "B.Tech"}, "Shyam": {"name": "Shyam", "SID": 99695, "Course": "B.Tech"}, "Ujjawal": {"name": "Ujjawal", "SID": 100087, "Course": "B.Tech"}, "Rahul": {"name": "Rahul", "SID": 90163, "Course": "B.Tech"}, "Anuj": {"name": "Anuj", "SID": 90161, "Course": "B.Tech"}}'

In [144]:
with open("book.txt",'w') as f:
    f.write(s)

In [145]:
f=open('book.txt','r')

In [146]:
s=f.read()

In [147]:
s

'{"Sandeep": {"name": "Sandeep", "SID": 96674, "Course": "B.Tech"}, "Pandey": {"name": "Pandey", "SID": 90765, "Course": "B.Tech"}, "Vivek": {"name": "Vivek", "SID": 100365, "Course": "B.Tech"}, "Shyam": {"name": "Shyam", "SID": 99695, "Course": "B.Tech"}, "Ujjawal": {"name": "Ujjawal", "SID": 100087, "Course": "B.Tech"}, "Rahul": {"name": "Rahul", "SID": 90163, "Course": "B.Tech"}, "Anuj": {"name": "Anuj", "SID": 90161, "Course": "B.Tech"}}'

In [148]:
import json
record=json.loads(s)

In [149]:
record

{'Sandeep': {'name': 'Sandeep', 'SID': 96674, 'Course': 'B.Tech'},
 'Pandey': {'name': 'Pandey', 'SID': 90765, 'Course': 'B.Tech'},
 'Vivek': {'name': 'Vivek', 'SID': 100365, 'Course': 'B.Tech'},
 'Shyam': {'name': 'Shyam', 'SID': 99695, 'Course': 'B.Tech'},
 'Ujjawal': {'name': 'Ujjawal', 'SID': 100087, 'Course': 'B.Tech'},
 'Rahul': {'name': 'Rahul', 'SID': 90163, 'Course': 'B.Tech'},
 'Anuj': {'name': 'Anuj', 'SID': 90161, 'Course': 'B.Tech'}}

In [150]:
type(record)

dict

In [151]:
record["Sandeep"]

{'name': 'Sandeep', 'SID': 96674, 'Course': 'B.Tech'}

In [152]:
for person in record:
    print(record[person])

{'name': 'Sandeep', 'SID': 96674, 'Course': 'B.Tech'}
{'name': 'Pandey', 'SID': 90765, 'Course': 'B.Tech'}
{'name': 'Vivek', 'SID': 100365, 'Course': 'B.Tech'}
{'name': 'Shyam', 'SID': 99695, 'Course': 'B.Tech'}
{'name': 'Ujjawal', 'SID': 100087, 'Course': 'B.Tech'}
{'name': 'Rahul', 'SID': 90163, 'Course': 'B.Tech'}
{'name': 'Anuj', 'SID': 90161, 'Course': 'B.Tech'}


In [153]:
__name__

'__main__'

In [154]:
def calculate_area(base,height):
    return 1/2*(base*height)


if __name__=="__main__":
    a=calculate_area(10,20)
    print('area:',a)

area: 100.0


In [155]:
#raised error
1/0

ZeroDivisionError: division by zero

In [157]:
#reaised a type error
num1=input("Enter First number")
num2=input("Enter Second Number")
num1/num2

Enter First number45
Enter Second Number65


TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [158]:
class Human:
    def __init__(self,name):
        self.name=name
    def do_work(self):
        if self.name=="Sandeep":
            print(self.name,"Student")
        else:
            print("Other Occupation")

In [159]:
sandy=Human("Sandeep")

In [160]:
sandy.do_work()

Sandeep Student


In [161]:
sandy.name

'Sandeep'

In [162]:
vivek=Human("Vivek")

In [163]:
vivek.do_work()

Other Occupation


In [164]:
vivek.name

'Vivek'

In [165]:
a=[1,2,2,3,435,6,67,7,6,231,234]

In [166]:
a

[1, 2, 2, 3, 435, 6, 67, 7, 6, 231, 234]

In [167]:
for i in a:
    print(i)

1
2
2
3
435
6
67
7
6
231
234


In [168]:
a.sort()

In [169]:
dir(a)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [170]:
itr=iter(a)

In [171]:
itr

In [172]:
next(itr)

1

In [173]:
next(itr)

2

In [174]:
itr2=reversed(a)

In [175]:
itr2

In [176]:
next(itr2)

435

In [177]:
next(itr2)

234

In [178]:
dir('yield')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [179]:
def fib():
    a,b=0,1
    while True:
        yield a
        a,b=b,a+b
for f in fib():
    if f>100:
        break
    print(f)

0
1
1
2
3
5
8
13
21
34
55
89


In [180]:
num=[1,2,34,54,5,35,631,3,43,121,13,414,31,1]

In [181]:
even=[]
for i in num:
    if i%2==0:
        even.append(i)

In [182]:
even

[2, 34, 54, 414]

In [183]:
#Comprehensive
even2=[i for i in num if i%2==0]

In [184]:
even2

[2, 34, 54, 414]

In [185]:
odd=[i for i in num if i%2 !=0]

In [186]:
odd

[1, 5, 35, 631, 3, 43, 121, 13, 31, 1]

In [187]:
sqr=[i*i for i in num]

In [188]:
sqr

[1, 4, 1156, 2916, 25, 1225, 398161, 9, 1849, 14641, 169, 171396, 961, 1]

In [189]:
s=set([1,2,3,4,5,6,2,5])

In [190]:
s

{1, 2, 3, 4, 5, 6}

In [191]:
ev={i for i in s if i%2==0}

In [192]:
ev

{2, 4, 6}

In [193]:
cities=['Mumbai','New York','Paris','Kolambo']
countries=['India','USA','France','Sri Lanka']

In [194]:
z=zip(cities,countries)

In [195]:
z

In [196]:
for i in z:
    print(i)

('Mumbai', 'India')
('New York', 'USA')
('Paris', 'France')
('Kolambo', 'Sri Lanka')


In [197]:
d={city:country for city,country in zip(cities,countries)}

In [198]:
d

{'Mumbai': 'India',
 'New York': 'USA',
 'Paris': 'France',
 'Kolambo': 'Sri Lanka'}

In [199]:
d={country:city for city,country in zip(cities,countries)}

In [200]:
d

{'India': 'Mumbai',
 'USA': 'New York',
 'France': 'Paris',
 'Sri Lanka': 'Kolambo'}

In [201]:
a={}

In [202]:
type(a)

dict

In [203]:
b={"Sandeep"}

In [204]:
type(b)

set

In [205]:
c={"Name":"Sandeep"}

In [206]:
type(c)

dict

In [207]:
!pip install pytest

In [208]:
import numpy as np

In [209]:
a=np.array([12,23,324,235,135,15,16])

In [210]:
a

array([ 12,  23, 324, 235, 135,  15,  16])

In [211]:
type(a)

numpy.ndarray

In [212]:
import time
import sys

In [213]:
l=range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [214]:
array=np.arange(1000)
print(array.size*array.itemsize)

4000


In [215]:
size=10000000

In [216]:
l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("Time taken by the list",(time.time()-start)*1000)


start=time.time()
result=a1+a2
print("Time taken by Numpy",(time.time()-start)*1000)

Time taken by the list 1635.8208656311035
Time taken by Numpy 198.18353652954102


In [217]:
arr=np.array([1,2,3,4,5,5])

In [218]:
arr

array([1, 2, 3, 4, 5, 5])

In [219]:
arr.all()

True

In [220]:
arr.ndim

1

In [221]:
arr=np.array([[1,2,3],[1,134,53],[135,13,62]])

In [222]:
arr

array([[  1,   2,   3],
       [  1, 134,  53],
       [135,  13,  62]])

In [223]:
arr.ndim

2

In [224]:
arr.itemsize

4

In [225]:
a.dtype

dtype('int32')

In [226]:
arr2=np.array([[1,2,3],[1,134,53],[135,13,62]],dtype=float)

In [227]:
arr2

array([[  1.,   2.,   3.],
       [  1., 134.,  53.],
       [135.,  13.,  62.]])

In [228]:
arr2.dtype

dtype('float64')

In [229]:
arr2.size

9

In [230]:
arr.shape

(3, 3)

In [231]:
num=np.linspace(1,5,20)

In [232]:
num

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [233]:
num.ndim

1

In [234]:
num.reshape(4,5)

array([[1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526],
       [2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684],
       [3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842],
       [4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [235]:
num.reshape(5,4)

array([[1.        , 1.21052632, 1.42105263, 1.63157895],
       [1.84210526, 2.05263158, 2.26315789, 2.47368421],
       [2.68421053, 2.89473684, 3.10526316, 3.31578947],
       [3.52631579, 3.73684211, 3.94736842, 4.15789474],
       [4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [236]:
num.reshape(20,1)

array([[1.        ],
       [1.21052632],
       [1.42105263],
       [1.63157895],
       [1.84210526],
       [2.05263158],
       [2.26315789],
       [2.47368421],
       [2.68421053],
       [2.89473684],
       [3.10526316],
       [3.31578947],
       [3.52631579],
       [3.73684211],
       [3.94736842],
       [4.15789474],
       [4.36842105],
       [4.57894737],
       [4.78947368],
       [5.        ]])

In [237]:
num.reshape(2,10)

array([[1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684],
       [3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [238]:
num.ravel()

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [239]:
num.max()

5.0

In [240]:
num.sum(axis=0)

60.00000000000001

In [241]:
num.reshape(2,5,2)

array([[[1.        , 1.21052632],
        [1.42105263, 1.63157895],
        [1.84210526, 2.05263158],
        [2.26315789, 2.47368421],
        [2.68421053, 2.89473684]],

       [[3.10526316, 3.31578947],
        [3.52631579, 3.73684211],
        [3.94736842, 4.15789474],
        [4.36842105, 4.57894737],
        [4.78947368, 5.        ]]])

In [242]:
size=100000000

l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

#Time analysis for normal list
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("Time taken by the list",(time.time()-start)*1000)

#time analysis for Numpy
start=time.time()
result=a1+a2
print("Time taken by Numpy",(time.time()-start)*1000)

Time taken by the list 12857.37133026123
Time taken by Numpy 1253.713846206665


In [243]:
new=np.arange(30)

In [244]:
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [245]:
np.hsplit(new,5)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23]),
 array([24, 25, 26, 27, 28, 29])]

In [246]:
new.ndim

1

In [247]:
new.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [248]:
s=np.arange(10).reshape(2,5)

In [249]:
s

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [250]:
k= s>5 
k

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [251]:
s[k]

array([6, 7, 8, 9])

In [252]:
a=np.array([1,2,3,4],dtype=int)
b=np.array([2,4,6,8],dtype=float)
a*b

array([ 2.,  8., 18., 32.])

In [253]:
b.nbytes

32

In [254]:
c=np.arange(1,15).reshape(2,7)

In [255]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [256]:
c[1,5]

13

In [257]:
c[1,-2]

13

In [258]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [259]:
c[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [260]:
c[:,1]

array([2, 9])

In [261]:
c[0,1:6:2]

array([2, 4, 6])

In [262]:
c[1,3]=25

In [263]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 25, 12, 13, 14]])

In [264]:
z=np.zeros((2,3,3,4))

In [265]:
z

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [266]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [267]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [268]:
np.full((2,3),10,dtype=float)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [269]:
z.ndim

4

In [270]:
np.full((2,3),"Matrix")

array([['Matrix', 'Matrix', 'Matrix'],
       ['Matrix', 'Matrix', 'Matrix']], dtype='<U6')

In [271]:
import random
np.random.rand(1,3,4)

array([[[0.81120718, 0.53847935, 0.42382676, 0.22852859],
        [0.24913943, 0.27347829, 0.83193657, 0.38629256],
        [0.56263561, 0.45832752, 0.41894046, 0.16985775]]])

In [272]:
import random
np.random.rand(1,3,4).reshape(2,6)

array([[0.6978274 , 0.29295253, 0.25144954, 0.7000411 , 0.14240679,
        0.61148738],
       [0.2263203 , 0.9900056 , 0.60002556, 0.07481724, 0.48482831,
        0.07381256]])

In [273]:
np.random.rand(4,3)

array([[0.00239495, 0.31329048, 0.26006353],
       [0.12010432, 0.94088527, 0.23556928],
       [0.44896794, 0.7734174 , 0.26125875],
       [0.803015  , 0.60747787, 0.06293087]])

In [274]:
np.random.randint(7,size=(3,4))

array([[3, 6, 2, 2],
       [5, 2, 0, 0],
       [3, 3, 2, 5]])

In [275]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [276]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [277]:
output=np.ones((5,5),dtype=int)
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [278]:
z=np.zeros((3,3),dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [279]:
z[1,1]=9

In [280]:
z

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [281]:
output[1:4,1:4]=z

In [282]:
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [283]:
a=np.array([1,2,3])
b=a
b[1]=56
print(a)
b

[ 1 56  3]


array([ 1, 56,  3])

In [284]:
a=np.array([1,2,3])
b=a.copy()
b[1]=56
print(a)
b

[1 2 3]


array([ 1, 56,  3])

In [285]:
a

array([1, 2, 3])

In [286]:
a=np.array([1,2,3,4])

In [287]:
a**2

array([ 1,  4,  9, 16])

In [288]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [289]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [290]:
#Linear Algebra
import random

m1=random.randint(1,4)

In [291]:
m1

1

In [292]:
c=np.identity(3)

In [293]:
np.linalg.det(c)

1.0

In [294]:
m2=np.array([[1,2,3],[4,5,6]])
np.min(m2)

1

In [295]:
np.sum((a),axis=0)

10

In [296]:
np.genfromtxt('book.txt')

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [297]:
#index with a list in Numpy
m3=np.array([1,2,3,4,5,6,7,8,9])

In [298]:
m3[[2,5,7]]

array([3, 6, 8])

In [299]:
m3[m3>5]

array([6, 7, 8, 9])

In [300]:
np.any(m3>4,axis=0)

True

In [301]:
~(True)

-2

In [302]:
m4=np.arange(1,31).reshape(6,5)

In [303]:
m4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [304]:
m4[2,0:2]

array([11, 12])

In [305]:
m4[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [306]:
m4[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [312]:
for i in m4:
    if np.any(i<6):
        print(m4[i+1])
        i=i+1
    else:
        break

IndexError: index 6 is out of bounds for axis 0 with size 6

In [313]:
a=2
b=a
b

2

In [314]:
id(a)

1849327315280

In [315]:
id(b)

1849327315280

In [316]:
b=7

In [317]:
a

2

In [318]:
a=b

In [319]:
a

7

### Working with Pandas

In [320]:
import pandas as pd

In [321]:
# df=pd.read_excel
# df=pd.read_json


#Reading and Storing the Datasset in "df" variable
df=pd.read_csv('train.csv')

In [322]:
df.head(7)

User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000001  P00069042      F   0-17          10             A   
1  1000001  P00248942      F   0-17          10             A   
2  1000001  P00087842      F   0-17          10             A   
3  1000001  P00085442      F   0-17          10             A   
4  1000002  P00285442      M    55+          16             C   
5  1000003  P00193542      M  26-35          15             A   
6  1000004  P00184942      M  46-50           7             B   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   
5                          3               0                   1   
6                          2               1                   1   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969  
5                 2.0                 NaN     15227  
6                 8.0                17.0     19215

In [323]:
# checking the null values present in the Each Columns
df.isnull()

User_ID  Product_ID  Gender    Age  Occupation  City_Category  \
0         False       False   False  False       False          False   
1         False       False   False  False       False          False   
2         False       False   False  False       False          False   
3         False       False   False  False       False          False   
4         False       False   False  False       False          False   
...         ...         ...     ...    ...         ...            ...   
550063    False       False   False  False       False          False   
550064    False       False   False  False       False          False   
550065    False       False   False  False       False          False   
550066    False       False   False  False       False          False   
550067    False       False   False  False       False          False   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                            False           False               False   
1                            False           False               False   
2                            False           False               False   
3                            False           False               False   
4                            False           False               False   
...                            ...             ...                 ...   
550063                       False           False               False   
550064                       False           False               False   
550065                       False           False               False   
550066                       False           False               False   
550067                       False           False               False   

        Product_Category_2  Product_Category_3  Purchase  
0                     True                True     False  
1                    False               False     False  
2                     True                True     False  
3                    False                True     False  
4                     True                True     False  
...                    ...                 ...       ...  
550063                True                True     False  
550064                True                True     False  
550065                True                True     False  
550066                True                True     False  
550067                True                True     False  

[550068 rows x 12 columns]

In [324]:
#The lowest/ Tail Data Entity of the Dataset
df.tail()

User_ID Product_ID Gender    Age  Occupation City_Category  \
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490

In [325]:
#Finding the Shape of the Dataset (Rows,Columns)
df.shape

(550068, 12)

In [326]:
#Checkiing the Datatype of Columns
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [327]:
#Finding the Columns name
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [328]:
#Counting the Unique entity present in the Dataset with respect to Columns 
df.nunique()

User_ID                        5891
Product_ID                     3631
Gender                            2
Age                               7
Occupation                       21
City_Category                     3
Stay_In_Current_City_Years        5
Marital_Status                    2
Product_Category_1               20
Product_Category_2               17
Product_Category_3               15
Purchase                      18105
dtype: int64

In [329]:
# Finding the sum of null entity present in a Column 
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [330]:
#Finding the Max value present in a Particular Column
df["User_ID"].max()

1006040

In [331]:
df["User_ID"].min()

1000001

In [332]:
#Counting the entity present in a Column
df.count()

User_ID                       550068
Product_ID                    550068
Gender                        550068
Age                           550068
Occupation                    550068
City_Category                 550068
Stay_In_Current_City_Years    550068
Marital_Status                550068
Product_Category_1            550068
Product_Category_2            376430
Product_Category_3            166821
Purchase                      550068
dtype: int64

In [333]:
#Finding the correlation between the Columns
df.corr()

User_ID  Occupation  Marital_Status  Product_Category_1  \
User_ID             1.000000   -0.023971        0.020443            0.003825   
Occupation         -0.023971    1.000000        0.024280           -0.007618   
Marital_Status      0.020443    0.024280        1.000000            0.019888   
Product_Category_1  0.003825   -0.007618        0.019888            1.000000   
Product_Category_2  0.001529   -0.000384        0.015138            0.540583   
Product_Category_3  0.003419    0.013263        0.019473            0.229678   
Purchase            0.004716    0.020833       -0.000463           -0.343703   

                    Product_Category_2  Product_Category_3  Purchase  
User_ID                       0.001529            0.003419  0.004716  
Occupation                   -0.000384            0.013263  0.020833  
Marital_Status                0.015138            0.019473 -0.000463  
Product_Category_1            0.540583            0.229678 -0.343703  
Product_Category_2            1.000000            0.543649 -0.209918  
Product_Category_3            0.543649            1.000000 -0.022006  
Purchase                     -0.209918           -0.022006  1.000000

In [334]:
df.isna()

User_ID  Product_ID  Gender    Age  Occupation  City_Category  \
0         False       False   False  False       False          False   
1         False       False   False  False       False          False   
2         False       False   False  False       False          False   
3         False       False   False  False       False          False   
4         False       False   False  False       False          False   
...         ...         ...     ...    ...         ...            ...   
550063    False       False   False  False       False          False   
550064    False       False   False  False       False          False   
550065    False       False   False  False       False          False   
550066    False       False   False  False       False          False   
550067    False       False   False  False       False          False   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                            False           False               False   
1                            False           False               False   
2                            False           False               False   
3                            False           False               False   
4                            False           False               False   
...                            ...             ...                 ...   
550063                       False           False               False   
550064                       False           False               False   
550065                       False           False               False   
550066                       False           False               False   
550067                       False           False               False   

        Product_Category_2  Product_Category_3  Purchase  
0                     True                True     False  
1                    False               False     False  
2                     True                True     False  
3                    False                True     False  
4                     True                True     False  
...                    ...                 ...       ...  
550063                True                True     False  
550064                True                True     False  
550065                True                True     False  
550066                True                True     False  
550067                True                True     False  

[550068 rows x 12 columns]

In [335]:
#Basic Stats of the Whole Dataset e.g. Count, Mean, Max, Min, Standard Deviation
df.describe()

User_ID     Occupation  Marital_Status  Product_Category_1  \
count  5.500680e+05  550068.000000   550068.000000       550068.000000   
mean   1.003029e+06       8.076707        0.409653            5.404270   
std    1.727592e+03       6.522660        0.491770            3.936211   
min    1.000001e+06       0.000000        0.000000            1.000000   
25%    1.001516e+06       2.000000        0.000000            1.000000   
50%    1.003077e+06       7.000000        0.000000            5.000000   
75%    1.004478e+06      14.000000        1.000000            8.000000   
max    1.006040e+06      20.000000        1.000000           20.000000   

       Product_Category_2  Product_Category_3       Purchase  
count       376430.000000       166821.000000  550068.000000  
mean             9.842329           12.668243    9263.968713  
std              5.086590            4.125338    5023.065394  
min              2.000000            3.000000      12.000000  
25%              5.000000            9.000000    5823.000000  
50%              9.000000           14.000000    8047.000000  
75%             15.000000           16.000000   12054.000000  
max             18.000000           18.000000   23961.000000

In [336]:
df.Age

0          0-17
1          0-17
2          0-17
3          0-17
4           55+
          ...  
550063    51-55
550064    26-35
550065    26-35
550066      55+
550067    46-50
Name: Age, Length: 550068, dtype: object

In [337]:
df.index

RangeIndex(start=0, stop=550068, step=1)

In [338]:
g=df.groupby('Gender')

In [339]:
g

In [340]:

for Gender , Gender_df in g:
    print(Gender)
    print(Gender_df)

F
        User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
14      1000006  P00231342      F  51-55           9             A   
...         ...        ...    ...    ...         ...           ...   
550061  1006029  P00372445      F  26-35           1             C   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1          

In [341]:
g.get_group('F')

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
14      1000006  P00231342      F  51-55           9             A   
...         ...        ...    ...    ...         ...           ...   
550061  1006029  P00372445      F  26-35           1             C   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
14                              1               0                   5   
...                           ...             ...                 ...   
550061                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
14                     8.0                14.0      5378  
...                    ...                 ...       ...  
550061                 NaN                 NaN       599  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[135809 rows x 12 columns]

In [342]:
g.get_group('M')

User_ID Product_ID Gender    Age  Occupation City_Category  \
4       1000002  P00285442      M    55+          16             C   
5       1000003  P00193542      M  26-35          15             A   
6       1000004  P00184942      M  46-50           7             B   
7       1000004  P00346142      M  46-50           7             B   
8       1000004   P0097242      M  46-50           7             B   
...         ...        ...    ...    ...         ...           ...   
550057  1006023  P00370853      M  26-35           0             C   
550058  1006024  P00372445      M  26-35          12             A   
550060  1006026  P00371644      M  36-45           6             C   
550062  1006032  P00372445      M  46-50           7             A   
550063  1006033  P00372445      M  51-55          13             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
4                              4+               0                   8   
5                               3               0                   1   
6                               2               1                   1   
7                               2               1                   1   
8                               2               1                   1   
...                           ...             ...                 ...   
550057                          2               1                  19   
550058                          0               1                  20   
550060                          1               1                  20   
550062                          3               0                  20   
550063                          1               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
4                      NaN                 NaN      7969  
5                      2.0                 NaN     15227  
6                      8.0                17.0     19215  
7                     15.0                 NaN     15854  
8                     16.0                 NaN     15686  
...                    ...                 ...       ...  
550057                 NaN                 NaN        61  
550058                 NaN                 NaN       121  
550060                 NaN                 NaN       494  
550062                 NaN                 NaN       473  
550063                 NaN                 NaN       368  

[414259 rows x 12 columns]

In [343]:
g.max()

User_ID Product_ID  Age  Occupation City_Category  \
Gender                                                      
F       1006039   P0099942  55+          20             C   
M       1006040   P0099942  55+          20             C   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
Gender                                                                  
F                              4+               1                  20   
M                              4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
Gender                                                    
F                     18.0                18.0     23959  
M                     18.0                18.0     23961

In [344]:
g.describe()

User_ID                                                              \
           count          mean          std        min        25%        50%   
Gender                                                                         
F       135809.0  1.003130e+06  1786.630589  1000001.0  1001569.0  1003159.0   
M       414259.0  1.002996e+06  1706.493873  1000002.0  1001505.0  1003041.0   

                             Occupation           ... Product_Category_3  \
              75%        max      count     mean  ...                75%   
Gender                                            ...                      
F       1004765.0  1006039.0   135809.0  6.74054  ...               16.0   
M       1004411.0  1006040.0   414259.0  8.51475  ...               16.0   

              Purchase                                                  \
         max     count         mean          std   min     25%     50%   
Gender                                                                   
F       18.0  135809.0  8734.565765  4767.233289  12.0  5433.0  7914.0   
M       18.0  414259.0  9437.526040  5092.186210  12.0  5863.0  8098.0   

                          
            75%      max  
Gender                    
F       11400.0  23959.0  
M       12454.0  23961.0  

[2 rows x 56 columns]

In [345]:
df2=df

In [346]:
df2

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
...                    ...                 ...       ...  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[550068 rows x 12 columns]

In [347]:
df3=df

In [348]:
df3

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
...                    ...                 ...       ...  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[550068 rows x 12 columns]

In [349]:
new_df=pd.concat([df2,df3],ignore_index=True)

In [350]:
new_df

User_ID Product_ID Gender    Age  Occupation City_Category  \
0        1000001  P00069042      F   0-17          10             A   
1        1000001  P00248942      F   0-17          10             A   
2        1000001  P00087842      F   0-17          10             A   
3        1000001  P00085442      F   0-17          10             A   
4        1000002  P00285442      M    55+          16             C   
...          ...        ...    ...    ...         ...           ...   
1100131  1006033  P00372445      M  51-55          13             B   
1100132  1006035  P00375436      F  26-35           1             C   
1100133  1006036  P00375436      F  26-35          15             B   
1100134  1006038  P00375436      F    55+           1             C   
1100135  1006039  P00371644      F  46-50           0             B   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                                2               0                   3   
1                                2               0                   1   
2                                2               0                  12   
3                                2               0                  12   
4                               4+               0                   8   
...                            ...             ...                 ...   
1100131                          1               1                  20   
1100132                          3               0                  20   
1100133                         4+               1                  20   
1100134                          2               0                  20   
1100135                         4+               1                  20   

         Product_Category_2  Product_Category_3  Purchase  
0                       NaN                 NaN      8370  
1                       6.0                14.0     15200  
2                       NaN                 NaN      1422  
3                      14.0                 NaN      1057  
4                       NaN                 NaN      7969  
...                     ...                 ...       ...  
1100131                 NaN                 NaN       368  
1100132                 NaN                 NaN       371  
1100133                 NaN                 NaN       137  
1100134                 NaN                 NaN       365  
1100135                 NaN                 NaN       490  

[1100136 rows x 12 columns]

In [351]:
new_df.shape

(1100136, 12)

In [352]:
new_df2=pd.concat([df2,df3],keys=['df2','df3'])

In [353]:
new_df2

User_ID Product_ID Gender    Age  Occupation City_Category  \
df2 0       1000001  P00069042      F   0-17          10             A   
    1       1000001  P00248942      F   0-17          10             A   
    2       1000001  P00087842      F   0-17          10             A   
    3       1000001  P00085442      F   0-17          10             A   
    4       1000002  P00285442      M    55+          16             C   
...             ...        ...    ...    ...         ...           ...   
df3 550063  1006033  P00372445      M  51-55          13             B   
    550064  1006035  P00375436      F  26-35           1             C   
    550065  1006036  P00375436      F  26-35          15             B   
    550066  1006038  P00375436      F    55+           1             C   
    550067  1006039  P00371644      F  46-50           0             B   

           Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
df2 0                               2               0                   3   
    1                               2               0                   1   
    2                               2               0                  12   
    3                               2               0                  12   
    4                              4+               0                   8   
...                               ...             ...                 ...   
df3 550063                          1               1                  20   
    550064                          3               0                  20   
    550065                         4+               1                  20   
    550066                          2               0                  20   
    550067                         4+               1                  20   

            Product_Category_2  Product_Category_3  Purchase  
df2 0                      NaN                 NaN      8370  
    1                      6.0                14.0     15200  
    2                      NaN                 NaN      1422  
    3                     14.0                 NaN      1057  
    4                      NaN                 NaN      7969  
...                        ...                 ...       ...  
df3 550063                 NaN                 NaN       368  
    550064                 NaN                 NaN       371  
    550065                 NaN                 NaN       137  
    550066                 NaN                 NaN       365  
    550067                 NaN                 NaN       490  

[1100136 rows x 12 columns]

In [354]:
new_df2.loc['df2']

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
...                    ...                 ...       ...  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[550068 rows x 12 columns]

In [355]:
#Cross Table or Contingency Table
pd.crosstab(new_df2.Age,new_df2.City_Category,margins=True)

City_Category       A       B       C      All
Age                                           
0-17             5088   10870   14246    30204
18-25           55070   86494   57756   199320
26-35          147490  183168  108516   439174
36-45           53234   95196   71596   220026
46-50           15214   40812   35376    91402
51-55           12198   35482   29322    77002
55+              7146   10324   25538    43008
All            295440  462346  342350  1100136

In [1]:
import pandas as pd