In [120]:
print("Hello World")

Hello World


In [121]:
c=1+2j

In [122]:
type(c)

complex

In [123]:
del (c)

In [124]:
print(c)

NameError: name 'c' is not defined

$a=b+c$

In [125]:
%whos

Variable   Type      Data/Info
------------------------------
a          float     1212431.315341
address    str       Jaipur, Rajasthan
area       float     25.0
b          int       3
base       int       10
d          int       -34
details    list      n=10
e          float     45.2
expense    list      n=8
f          int       10
first      int       2
height     int       5
i          int       7
l          list      n=10
name       str       Sandeep Kumar
name1      str       Sandeep
name2      str       Vivek
name3      str       Shyam
names      list      n=5
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
s          str       Sandeep
second     int       3
sid        list      n=5
sys        module    <module 'sys' (built-in)>
third      int       5
total      int       3058
x          float     1212431.315341


In [126]:
b,c,d,e,f=1,14,-34,45.2,10

In [127]:
%whos

Variable   Type      Data/Info
------------------------------
a          float     1212431.315341
address    str       Jaipur, Rajasthan
area       float     25.0
b          int       1
base       int       10
c          int       14
d          int       -34
details    list      n=10
e          float     45.2
expense    list      n=8
f          int       10
first      int       2
height     int       5
i          int       7
l          list      n=10
name       str       Sandeep Kumar
name1      str       Sandeep
name2      str       Vivek
name3      str       Shyam
names      list      n=5
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
s          str       Sandeep
second     int       3
sid        list      n=5
sys        module    <module 'sys' (built-in)>
third      int       5
total      int       3058
x          float     1212431.315341


In [128]:
%whos

Variable   Type      Data/Info
------------------------------
a          float     1212431.315341
address    str       Jaipur, Rajasthan
area       float     25.0
b          int       1
base       int       10
c          int       14
d          int       -34
details    list      n=10
e          float     45.2
expense    list      n=8
f          int       10
first      int       2
height     int       5
i          int       7
l          list      n=10
name       str       Sandeep Kumar
name1      str       Sandeep
name2      str       Vivek
name3      str       Shyam
names      list      n=5
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
s          str       Sandeep
second     int       3
sid        list      n=5
sys        module    <module 'sys' (built-in)>
third      int       5
total      int       3058
x          float     1212431.315341


In [129]:
x=90

In [130]:
%whos

Variable   Type      Data/Info
------------------------------
a          float     1212431.315341
address    str       Jaipur, Rajasthan
area       float     25.0
b          int       1
base       int       10
c          int       14
d          int       -34
details    list      n=10
e          float     45.2
expense    list      n=8
f          int       10
first      int       2
height     int       5
i          int       7
l          list      n=10
name       str       Sandeep Kumar
name1      str       Sandeep
name2      str       Vivek
name3      str       Shyam
names      list      n=5
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
s          str       Sandeep
second     int       3
sid        list      n=5
sys        module    <module 'sys' (built-in)>
third      int       5
total      int       3058
x          int       90


In [131]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [132]:
s="How are you buddy"

In [133]:
s

'How are you buddy'

In [134]:
print(type(s))

<class 'str'>


In [135]:
type(s)

str

In [136]:
a="Sandeep"

In [137]:
a

'Sandeep'

In [138]:
_

'Sandeep'

In [139]:
b="New"

In [140]:
b

'New'

In [141]:
_

'New'

In [142]:
%whos

Variable   Type      Data/Info
------------------------------
a          str       Sandeep
address    str       Jaipur, Rajasthan
area       float     25.0
b          str       New
base       int       10
c          int       14
d          int       -34
details    list      n=10
e          float     45.2
expense    list      n=8
f          int       10
first      int       2
height     int       5
i          int       7
l          list      n=10
name       str       Sandeep Kumar
name1      str       Sandeep
name2      str       Vivek
name3      str       Shyam
names      list      n=5
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
s          str       How are you buddy
second     int       3
sid        list      n=5
sys        module    <module 'sys' (built-in)>
third      int       5
total      int       3058
x          int       90


In [143]:
'a'>'A'

True

In [144]:
2!=3

True

In [145]:
not True and True and True

False

In [146]:
print(round(7.5))

8


In [147]:
divmod(24,5)

(4, 4)

In [148]:
divmod(2,1)

(2, 0)

In [149]:
isinstance(1,int)

True

In [150]:
pow(2,5)

32

In [151]:
pow(2,4,3)

1

In [152]:
help(input)

Help on method raw_input in module ipykernel.kernelbase:

raw_input(prompt='') method of ipykernel.ipkernel.IPythonKernel instance
    Forward raw_input to frontends
    
    Raises
    ------
    StdinNotImplementedError if active frontend doesn't support stdin.



In [153]:
l=[]
for i in range(10):
    print(i+1)
    l.append(i**2)
print(l)

1
2
3
4
5
6
7
8
9
10
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [154]:
import numpy as np
"""Importing numpy for Numerical Analysis
"""

'Importing numpy for Numerical Analysis\n'

In [155]:
np?

In [156]:
len??

In [157]:
import sys

In [158]:
s="Sandeep"
a="Kumar"

In [159]:
print(type(a))

<class 'str'>


In [160]:
type(s)

str

In [161]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,43,4,5])

In [162]:
np.intersect1d(a,b)

array([1, 2, 4, 5])

In [163]:
print(type(a))

<class 'numpy.ndarray'>


In [164]:
print(type(b))

<class 'numpy.ndarray'>


In [165]:
a.dtype

dtype('int32')

In [166]:
print(a.ndim)

1


In [167]:
print(b.ndim)

1


In [168]:
print(b.shape[0])

5


In [169]:
c=np.array([[[1,2,3],[4,5,0],12,6,7]])

C:\Users\sande\AppData\Local\Temp\ipykernel_16928\340799500.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[[1,2,3],[4,5,0],12,6,7]])


In [170]:
c.ndim

2

In [171]:
c[0,1]

[4, 5, 0]

In [172]:
a=2
b=3
c=5

In [173]:
first=a
second=b
third=c

In [174]:
dir(a)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [175]:
id(a)

1571156486480

In [176]:
a="Sandeep"

In [177]:
id(a)

1571271825648

In [178]:
x=1212431.315341

In [179]:
round(x)

1212431

In [180]:
round(x,4)

1212431.3153

In [181]:
10+2*3

16

In [182]:
(10+2)*3

36

In [183]:
6-5.7

0.2999999999999998

In [184]:
round(6-5.7,2)

0.3

In [185]:
name="Sandeep Kumar"

In [186]:
name[1]

'a'

In [187]:
name[7]

' '

In [188]:
name[3:11]

'deep Kum'

In [189]:
name[::]

'Sandeep Kumar'

In [190]:
name[0:]

'Sandeep Kumar'

In [191]:
address='''Jaipur, Rajasthan'''

In [192]:
address

'Jaipur, Rajasthan'

In [193]:
name1="Sandeep"
name2="Vivek"
name3="Shyam"
names=[name1,name2,name3]

In [194]:
names

['Sandeep', 'Vivek', 'Shyam']

In [195]:
names.append("Pandey")

In [196]:
names

['Sandeep', 'Vivek', 'Shyam', 'Pandey']

In [197]:
names.insert(1,"Anuj")

In [198]:
names

['Sandeep', 'Anuj', 'Vivek', 'Shyam', 'Pandey']

In [199]:
sid=[96674,90161,100365,99695,90765]

In [200]:
details=names+sid

In [201]:
details

['Sandeep',
 'Anuj',
 'Vivek',
 'Shyam',
 'Pandey',
 96674,
 90161,
 100365,
 99695,
 90765]

In [202]:
len(details)

10

In [203]:
"Sandeep" in details

True

In [204]:
"Kuldeep" in details

False

In [205]:
base=10
height=5
area=1/2*(base*height)

In [206]:
area

25.0

In [207]:
expense=[12,1224,14,1234,14,134,314,112]
total=0
for i in expense:
    total+=i
print(total)

3058


In [208]:
for i in expense:
    print("expense is: ",i)

expense is:  12
expense is:  1224
expense is:  14
expense is:  1234
expense is:  14
expense is:  134
expense is:  314
expense is:  112


In [209]:
for i in range(0,11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [210]:
for i in range(len(expense)):
    print('Month:',(i+1),"Expense:",expense[i])

Month: 1 Expense: 12
Month: 2 Expense: 1224
Month: 3 Expense: 14
Month: 4 Expense: 1234
Month: 5 Expense: 14
Month: 6 Expense: 134
Month: 7 Expense: 314
Month: 8 Expense: 112


In [211]:
for i in range(1,50):
    if i%2==0 and i%3==0:
        print(f"The number {i} is divisible by 2 and 3 both")
    if i%3==0 and i%5==0:
        print(f"The number {i} is divisible by 3 and 5 both")
    else:
        print(f"The number is {i}")

The number is 1
The number is 2
The number is 3
The number is 4
The number is 5
The number 6 is divisible by 2 and 3 both
The number is 6
The number is 7
The number is 8
The number is 9
The number is 10
The number is 11
The number 12 is divisible by 2 and 3 both
The number is 12
The number is 13
The number is 14
The number 15 is divisible by 3 and 5 both
The number is 16
The number is 17
The number 18 is divisible by 2 and 3 both
The number is 18
The number is 19
The number is 20
The number is 21
The number is 22
The number is 23
The number 24 is divisible by 2 and 3 both
The number is 24
The number is 25
The number is 26
The number is 27
The number is 28
The number is 29
The number 30 is divisible by 2 and 3 both
The number 30 is divisible by 3 and 5 both
The number is 31
The number is 32
The number is 33
The number is 34
The number is 35
The number 36 is divisible by 2 and 3 both
The number is 36
The number is 37
The number is 38
The number is 39
The number is 40
The number is 41
The

In [212]:
!pip install numpy

In [213]:
import numpy as np

In [214]:
np.array([1,2,3])

array([1, 2, 3])

In [215]:
np.array([1,2,3.7],dtype=int)

array([1, 2, 3])

In [216]:
np.array([1,2,3.7],dtype=float)

array([1. , 2. , 3.7])

In [217]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [218]:
np.full((2,2),"Sandeep")

array([['Sandeep', 'Sandeep'],
       ['Sandeep', 'Sandeep']], dtype='<U7')

In [220]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [223]:
np.ones((7),dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

In [225]:
np.eye((4),dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [226]:
number=input("First Number") #23
number2=input("Second Number") #27
print(number+number2)

First Number23
Second Number27
2327
