In [1]:
print("Hello World")

Hello World


In [2]:
c=1+2j

In [3]:
type(c)

complex

In [4]:
del (c)

In [5]:
print(c)

NameError: name 'c' is not defined

$a=b+c$

In [6]:
%whos

Interactive namespace is empty.


In [7]:
b,c,d,e,f=1,14,-34,45.2,10

In [8]:
%whos

Variable   Type     Data/Info
-----------------------------
b          int      1
c          int      14
d          int      -34
e          float    45.2
f          int      10


In [9]:
%whos

Variable   Type     Data/Info
-----------------------------
b          int      1
c          int      14
d          int      -34
e          float    45.2
f          int      10


In [10]:
x=90

In [11]:
%whos

Variable   Type     Data/Info
-----------------------------
b          int      1
c          int      14
d          int      -34
e          float    45.2
f          int      10
x          int      90


In [12]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [13]:
s="How are you buddy"

In [14]:
s

'How are you buddy'

In [15]:
print(type(s))

<class 'str'>


In [16]:
type(s)

str

In [17]:
a="Sandeep"

In [18]:
a

'Sandeep'

In [19]:
_

'Sandeep'

In [20]:
b="New"

In [21]:
b

'New'

In [22]:
_

'New'

In [23]:
%whos

Variable   Type     Data/Info
-----------------------------
a          str      Sandeep
b          str      New
c          int      14
d          int      -34
e          float    45.2
f          int      10
s          str      How are you buddy
x          int      90


In [24]:
'a'>'A'

True

In [25]:
2!=3

True

In [26]:
not True and True and True

False

In [27]:
print(round(7.5))

8


In [28]:
divmod(24,5)

(4, 4)

In [29]:
divmod(2,1)

(2, 0)

In [30]:
isinstance(1,int)

True

In [31]:
pow(2,5)

32

In [32]:
pow(2,4,3)

1

In [33]:
help(input)

Help on method raw_input in module ipykernel.kernelbase:

raw_input(prompt='') method of ipykernel.ipkernel.IPythonKernel instance
    Forward raw_input to frontends
    
    Raises
    ------
    StdinNotImplementedError if active frontend doesn't support stdin.



In [34]:
l=[]
for i in range(10):
    print(i+1)
    l.append(i**2)
print(l)

1
2
3
4
5
6
7
8
9
10
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [35]:
import numpy as np
"""Importing numpy for Numerical Analysis
"""

'Importing numpy for Numerical Analysis\n'

In [36]:
np?

In [37]:
len??

In [38]:
import sys

In [39]:
s="Sandeep"
a="Kumar"

In [40]:
print(type(a))

<class 'str'>


In [41]:
type(s)

str

In [42]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,43,4,5])

In [43]:
np.intersect1d(a,b)

array([1, 2, 4, 5])

In [44]:
print(type(a))

<class 'numpy.ndarray'>


In [45]:
print(type(b))

<class 'numpy.ndarray'>


In [46]:
a.dtype

dtype('int32')

In [47]:
print(a.ndim)

1


In [48]:
print(b.ndim)

1


In [49]:
print(b.shape[0])

5


In [50]:
c=np.array([[[1,2,3],[4,5,0],12,6,7]])

C:\Users\sande\AppData\Local\Temp\ipykernel_29496\340799500.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[[1,2,3],[4,5,0],12,6,7]])


In [51]:
c.ndim

2

In [52]:
c[0,1]

[4, 5, 0]

In [53]:
a=2
b=3
c=5

In [54]:
first=a
second=b
third=c

In [55]:
dir(a)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [56]:
id(a)

1522809989456

In [57]:
a="Sandeep"

In [58]:
id(a)

1522925607856

In [59]:
x=1212431.315341

In [60]:
round(x)

1212431

In [61]:
round(x,4)

1212431.3153

In [62]:
10+2*3

16

In [63]:
(10+2)*3

36

In [64]:
6-5.7

0.2999999999999998

In [65]:
round(6-5.7,2)

0.3

In [66]:
name="Sandeep Kumar"

In [67]:
name[1]

'a'

In [68]:
name[7]

' '

In [69]:
name[3:11]

'deep Kum'

In [70]:
name[::]

'Sandeep Kumar'

In [71]:
name[0:]

'Sandeep Kumar'

In [72]:
address='''Jaipur, Rajasthan'''

In [73]:
address

'Jaipur, Rajasthan'

In [74]:
name1="Sandeep"
name2="Vivek"
name3="Shyam"
names=[name1,name2,name3]

In [75]:
names

['Sandeep', 'Vivek', 'Shyam']

In [76]:
names.append("Pandey")

In [77]:
names

['Sandeep', 'Vivek', 'Shyam', 'Pandey']

In [78]:
names.insert(1,"Anuj")

In [79]:
names

['Sandeep', 'Anuj', 'Vivek', 'Shyam', 'Pandey']

In [80]:
sid=[96674,90161,100365,99695,90765]

In [81]:
details=names+sid

In [82]:
details

['Sandeep',
 'Anuj',
 'Vivek',
 'Shyam',
 'Pandey',
 96674,
 90161,
 100365,
 99695,
 90765]

In [83]:
len(details)

10

In [84]:
"Sandeep" in details

True

In [85]:
"Kuldeep" in details

False

In [86]:
base=10
height=5
area=1/2*(base*height)

In [87]:
area

25.0

In [88]:
expense=[12,1224,14,1234,14,134,314,112]
total=0
for i in expense:
    total+=i
print(total)

3058


In [89]:
for i in expense:
    print("expense is: ",i)

expense is:  12
expense is:  1224
expense is:  14
expense is:  1234
expense is:  14
expense is:  134
expense is:  314
expense is:  112


In [90]:
for i in range(0,11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [91]:
for i in range(len(expense)):
    print('Month:',(i+1),"Expense:",expense[i])

Month: 1 Expense: 12
Month: 2 Expense: 1224
Month: 3 Expense: 14
Month: 4 Expense: 1234
Month: 5 Expense: 14
Month: 6 Expense: 134
Month: 7 Expense: 314
Month: 8 Expense: 112


In [92]:
for i in range(1,50):
    if i%2==0 and i%3==0:
        print(f"The number {i} is divisible by 2 and 3 both")
    if i%3==0 and i%5==0:
        print(f"The number {i} is divisible by 3 and 5 both")
    else:
        print(f"The number is {i}")

The number is 1
The number is 2
The number is 3
The number is 4
The number is 5
The number 6 is divisible by 2 and 3 both
The number is 6
The number is 7
The number is 8
The number is 9
The number is 10
The number is 11
The number 12 is divisible by 2 and 3 both
The number is 12
The number is 13
The number is 14
The number 15 is divisible by 3 and 5 both
The number is 16
The number is 17
The number 18 is divisible by 2 and 3 both
The number is 18
The number is 19
The number is 20
The number is 21
The number is 22
The number is 23
The number 24 is divisible by 2 and 3 both
The number is 24
The number is 25
The number is 26
The number is 27
The number is 28
The number is 29
The number 30 is divisible by 2 and 3 both
The number 30 is divisible by 3 and 5 both
The number is 31
The number is 32
The number is 33
The number is 34
The number is 35
The number 36 is divisible by 2 and 3 both
The number is 36
The number is 37
The number is 38
The number is 39
The number is 40
The number is 41
The

In [93]:
!pip install numpy

In [94]:
import numpy as np

In [95]:
np.array([1,2,3])

array([1, 2, 3])

In [96]:
np.array([1,2,3.7],dtype=int)

array([1, 2, 3])

In [97]:
np.array([1,2,3.7],dtype=float)

array([1. , 2. , 3.7])

In [98]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.full((2,2),"Sandeep")

array([['Sandeep', 'Sandeep'],
       ['Sandeep', 'Sandeep']], dtype='<U7')

In [100]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [101]:
np.ones((7),dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

In [102]:
np.eye((4),dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [105]:
number=input("First Number") #23
number2=input("Second Number") #27
print(number+number2)

First Number54
Second Number65
5465


In [106]:
import numpy as np
np.eye((4),dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])