### Get Start with Python

In [2]:
#the basic function
print("Hello World")

Hello World


In [3]:
dir(print)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

#### Defining a variable with `"Complex Datatype"`

In [4]:
# crearting a variable to store some data
c=1+2j

In [3]:
#fetching the imaginary part of the complex number
c.imag

2.0

#### Checking the `"Datatype"` of the variable

In [2]:
type(c)

complex

#### Delete the Varible from the Memory

In [3]:
del (c)

#### After deleting, try to access the Variable 

In [4]:
print(c)

NameError: name 'c' is not defined

$a=b+c$

#### Checking the all variable present in the `"Memory"`

In [6]:
%whos

Interactive namespace is empty.


#### defining multiple variables at a time

In [7]:
b,c,d,e,f=1,14,-34,45.2,10

#### Checking the all variable present in the `"Memory"`

In [8]:
%whos

Variable   Type     Data/Info
-----------------------------
b          int      1
c          int      14
d          int      -34
e          float    45.2
f          int      10


In [10]:
x=90

In [11]:
%whos

Variable   Type     Data/Info
-----------------------------
b          int      1
c          int      14
d          int      -34
e          float    45.2
f          int      10
x          int      90


In [12]:
#finding the function can be use on List
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [13]:
#defining a String
s="How are you buddy"

In [14]:
s

'How are you buddy'

In [15]:
print(type(s))

<class 'str'>


In [16]:
type(s)

str

In [17]:
a="Sandeep"

In [18]:
a

'Sandeep'

In [19]:
_

'Sandeep'

In [20]:
b="New"

In [21]:
b

'New'

In [22]:
_

'New'

In [23]:
%whos

Variable   Type     Data/Info
-----------------------------
a          str      Sandeep
b          str      New
c          int      14
d          int      -34
e          float    45.2
f          int      10
s          str      How are you buddy
x          int      90


In [24]:
'a'>'A'

True

In [25]:
2!=3

True

In [26]:
not True and True and True

False

In [27]:
print(round(7.5))

8


In [28]:
divmod(24,5)

(4, 4)

In [29]:
divmod(2,1)

(2, 0)

In [30]:
isinstance(1,int)

True

In [31]:
pow(2,5)

32

In [32]:
pow(2,4,3)

1

In [33]:
help(input)

Help on method raw_input in module ipykernel.kernelbase:

raw_input(prompt='') method of ipykernel.ipkernel.IPythonKernel instance
    Forward raw_input to frontends
    
    Raises
    ------
    StdinNotImplementedError if active frontend doesn't support stdin.



In [34]:
l=[]
for i in range(10):
    print(i+1)
    l.append(i**2)
print(l)

1
2
3
4
5
6
7
8
9
10
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [35]:
import numpy as np
"""Importing numpy for Numerical Analysis
"""

'Importing numpy for Numerical Analysis\n'

In [36]:
np?

In [37]:
len??

In [38]:
import sys

In [39]:
s="Sandeep"
a="Kumar"

In [40]:
print(type(a))

<class 'str'>


In [41]:
type(s)

str

In [42]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,43,4,5])

In [43]:
np.intersect1d(a,b)

array([1, 2, 4, 5])

In [44]:
print(type(a))

<class 'numpy.ndarray'>


In [45]:
print(type(b))

<class 'numpy.ndarray'>


In [46]:
a.dtype

dtype('int32')

In [47]:
print(a.ndim)

1


In [48]:
print(b.ndim)

1


In [49]:
print(b.shape[0])

5


In [50]:
c=np.array([[[1,2,3],[4,5,0],12,6,7]])

C:\Users\sande\AppData\Local\Temp\ipykernel_26292\340799500.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[[1,2,3],[4,5,0],12,6,7]])


In [51]:
c.ndim

2

In [52]:
c[0,1]

[4, 5, 0]

In [53]:
a=2
b=3
c=5

In [54]:
first=a
second=b
third=c

In [55]:
dir(a)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [56]:
id(a)

1776350357840

In [57]:
a="Sandeep"

In [58]:
id(a)

1776462298992

In [59]:
x=1212431.315341

In [60]:
round(x)

1212431

In [61]:
round(x,4)

1212431.3153

In [62]:
10+2*3

16

In [63]:
(10+2)*3

36

In [64]:
6-5.7

0.2999999999999998

In [65]:
round(6-5.7,2)

0.3

In [66]:
name="Sandeep Kumar"

In [67]:
name[1]

'a'

In [68]:
name[7]

' '

In [69]:
name[3:11]

'deep Kum'

In [70]:
name[::]

'Sandeep Kumar'

In [71]:
name[0:]

'Sandeep Kumar'

In [72]:
address='''Jaipur, Rajasthan'''

In [73]:
address

'Jaipur, Rajasthan'

In [74]:
name1="Sandeep"
name2="Vivek"
name3="Shyam"
names=[name1,name2,name3]

In [75]:
names

['Sandeep', 'Vivek', 'Shyam']

In [76]:
names.append("Pandey")

In [77]:
names

['Sandeep', 'Vivek', 'Shyam', 'Pandey']

In [78]:
names.insert(1,"Anuj")

In [79]:
names

['Sandeep', 'Anuj', 'Vivek', 'Shyam', 'Pandey']

In [80]:
sid=[96674,90161,100365,99695,90765]

In [81]:
details=names+sid

In [82]:
details

['Sandeep',
 'Anuj',
 'Vivek',
 'Shyam',
 'Pandey',
 96674,
 90161,
 100365,
 99695,
 90765]

In [83]:
len(details)

10

In [84]:
"Sandeep" in details

True

In [85]:
"Kuldeep" in details

False

In [86]:
base=10
height=5
area=1/2*(base*height)

In [87]:
area

25.0

In [88]:
expense=[12,1224,14,1234,14,134,314,112]
total=0
for i in expense:
    total+=i
print(total)

3058


In [89]:
for i in expense:
    print("expense is: ",i)

expense is:  12
expense is:  1224
expense is:  14
expense is:  1234
expense is:  14
expense is:  134
expense is:  314
expense is:  112


In [90]:
for i in range(0,11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [91]:
for i in range(len(expense)):
    print('Month:',(i+1),"Expense:",expense[i])

Month: 1 Expense: 12
Month: 2 Expense: 1224
Month: 3 Expense: 14
Month: 4 Expense: 1234
Month: 5 Expense: 14
Month: 6 Expense: 134
Month: 7 Expense: 314
Month: 8 Expense: 112


In [92]:
for i in range(1,50):
    if i%2==0 and i%3==0:
        print(f"The number {i} is divisible by 2 and 3 both")
    if i%3==0 and i%5==0:
        print(f"The number {i} is divisible by 3 and 5 both")
    else:
        print(f"The number is {i}")

The number is 1
The number is 2
The number is 3
The number is 4
The number is 5
The number 6 is divisible by 2 and 3 both
The number is 6
The number is 7
The number is 8
The number is 9
The number is 10
The number is 11
The number 12 is divisible by 2 and 3 both
The number is 12
The number is 13
The number is 14
The number 15 is divisible by 3 and 5 both
The number is 16
The number is 17
The number 18 is divisible by 2 and 3 both
The number is 18
The number is 19
The number is 20
The number is 21
The number is 22
The number is 23
The number 24 is divisible by 2 and 3 both
The number is 24
The number is 25
The number is 26
The number is 27
The number is 28
The number is 29
The number 30 is divisible by 2 and 3 both
The number 30 is divisible by 3 and 5 both
The number is 31
The number is 32
The number is 33
The number is 34
The number is 35
The number 36 is divisible by 2 and 3 both
The number is 36
The number is 37
The number is 38
The number is 39
The number is 40
The number is 41
The

In [93]:
!pip install numpy

In [5]:
import numpy as np

In [95]:
np.array([1,2,3])

array([1, 2, 3])

In [96]:
np.array([1,2,3.7],dtype=int)

array([1, 2, 3])

In [97]:
np.array([1,2,3.7],dtype=float)

array([1. , 2. , 3.7])

In [98]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.full((2,2),"Sandeep")

array([['Sandeep', 'Sandeep'],
       ['Sandeep', 'Sandeep']], dtype='<U7')

In [1]:
import numpy as np
zero_d=np.array(3)

In [2]:
zero_d.ndim # work as a 0 dimensional vector

0

##### Creating a `Zero Matrix` with defining their `Dimension`

In [100]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

##### Creating `One-dimensional` array with `1`

In [101]:
np.ones((7),dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

##### Creating an `Identity` with defining the `Data Type`

In [102]:
np.eye((4),dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [104]:
number=input("First Number") #23
number2=input("Second Number") #27
print(number+number2)

First Number23
Second Number27
2327


##### Creating an `identity` Matrix

In [105]:
import numpy as np
np.eye((4),dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### Creating a matrix with all `Zero Valued Element`

In [106]:
mat=np.zeros((3,3),dtype=float)

In [107]:
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### Returning the `Dimension` of the  Matrix

In [108]:
np.ndim(mat)

2

In [109]:
np.abs(23.2432)

23.2432

##### Returning the `Absolute Value`

In [110]:
np.absolute(23.2432)

23.2432

##### Adding two element

In [111]:
np.add(234,23)

257

##### Calculating the `max` element in a  List

In [112]:
np.amax([12,14,1234])

1234

##### Calculating `average` of List

In [113]:
np.average([123,123,41234,124,1234,1234,231])

6329.0

In [114]:
d={"Sandeep":96674,"Pandey":90765,"Vivek":100365}

In [115]:
d

{'Sandeep': 96674, 'Pandey': 90765, 'Vivek': 100365}

In [116]:
d.items()

dict_items([('Sandeep', 96674), ('Pandey', 90765), ('Vivek', 100365)])

In [117]:
d['Sandeep']

96674

In [118]:
d['Shyam']=99695

In [119]:
d

{'Sandeep': 96674, 'Pandey': 90765, 'Vivek': 100365, 'Shyam': 99695}

In [120]:
del d["Vivek"]

In [121]:
d

{'Sandeep': 96674, 'Pandey': 90765, 'Shyam': 99695}

In [122]:
for key in d:
    print("key:",key,"Value:",d[key])

key: Sandeep Value: 96674
key: Pandey Value: 90765
key: Shyam Value: 99695


In [123]:
for k,v in d.items():
    print('Key:',key,"Value:",d[key])

Key: Shyam Value: 99695
Key: Shyam Value: 99695
Key: Shyam Value: 99695


In [124]:
"Sandeep"in d

True

In [125]:
point=(1,2,34,4,1)

In [126]:
point[1]

2

In [127]:
id(point[0])

1776350357808

In [128]:
id(point[4])

1776350357808

In [129]:
id(point[3])

1776350357904

In [130]:
import math

In [131]:
math.sqrt(2)

1.4142135623730951

In [132]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [133]:
import calendar

In [134]:
cal=calendar.month(2016,1)

In [135]:
cal

'    January 2016\nMo Tu We Th Fr Sa Su\n             1  2  3\n 4  5  6  7  8  9 10\n11 12 13 14 15 16 17\n18 19 20 21 22 23 24\n25 26 27 28 29 30 31\n'

In [136]:
dir(calendar)

['Calendar',
 'EPOCH',
 'FRIDAY',
 'February',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'January',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MONDAY',
 'SATURDAY',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_monthlen',
 '_nextmonth',
 '_prevmonth',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthrange',
 'prcal',
 'prmonth',
 'prweek',
 'repeat',
 'setfirstweekday',
 'sys',
 'timegm',
 'week',
 'weekday',
 'weekheader']

In [137]:
book={}
book["Sandeep"]={
    'name':"Sandeep",
    'SID':96674,
    'Course':"B.Tech"
}
book["Pandey"]={
    'name':"Pandey",
    'SID':90765,
    'Course':"B.Tech"
}
book["Vivek"]={
    'name':"Vivek",
    'SID':100365,
    'Course':"B.Tech"
}
book["Shyam"]={
    'name':"Shyam",
    'SID':99695,
    'Course':"B.Tech"
}
book["Ujjawal"]={
    'name':"Ujjawal",
    'SID':100087,
    'Course':"B.Tech"
}
book["Rahul"]={
    'name':"Rahul",
    'SID':90163,
    'Course':"B.Tech"
}
book["Anuj"]={
    'name':"Anuj",
    'SID':90161,
    'Course':"B.Tech"
}

In [138]:
import json

In [139]:
s=json.dumps(book)

In [140]:
s

'{"Sandeep": {"name": "Sandeep", "SID": 96674, "Course": "B.Tech"}, "Pandey": {"name": "Pandey", "SID": 90765, "Course": "B.Tech"}, "Vivek": {"name": "Vivek", "SID": 100365, "Course": "B.Tech"}, "Shyam": {"name": "Shyam", "SID": 99695, "Course": "B.Tech"}, "Ujjawal": {"name": "Ujjawal", "SID": 100087, "Course": "B.Tech"}, "Rahul": {"name": "Rahul", "SID": 90163, "Course": "B.Tech"}, "Anuj": {"name": "Anuj", "SID": 90161, "Course": "B.Tech"}}'

In [141]:
with open("book.txt",'w') as f:
    f.write(s)

In [142]:
f=open('book.txt','r')

In [143]:
s=f.read()

In [144]:
s

'{"Sandeep": {"name": "Sandeep", "SID": 96674, "Course": "B.Tech"}, "Pandey": {"name": "Pandey", "SID": 90765, "Course": "B.Tech"}, "Vivek": {"name": "Vivek", "SID": 100365, "Course": "B.Tech"}, "Shyam": {"name": "Shyam", "SID": 99695, "Course": "B.Tech"}, "Ujjawal": {"name": "Ujjawal", "SID": 100087, "Course": "B.Tech"}, "Rahul": {"name": "Rahul", "SID": 90163, "Course": "B.Tech"}, "Anuj": {"name": "Anuj", "SID": 90161, "Course": "B.Tech"}}'

In [145]:
import json
record=json.loads(s)

In [146]:
record

{'Sandeep': {'name': 'Sandeep', 'SID': 96674, 'Course': 'B.Tech'},
 'Pandey': {'name': 'Pandey', 'SID': 90765, 'Course': 'B.Tech'},
 'Vivek': {'name': 'Vivek', 'SID': 100365, 'Course': 'B.Tech'},
 'Shyam': {'name': 'Shyam', 'SID': 99695, 'Course': 'B.Tech'},
 'Ujjawal': {'name': 'Ujjawal', 'SID': 100087, 'Course': 'B.Tech'},
 'Rahul': {'name': 'Rahul', 'SID': 90163, 'Course': 'B.Tech'},
 'Anuj': {'name': 'Anuj', 'SID': 90161, 'Course': 'B.Tech'}}

In [147]:
type(record)

dict

In [148]:
record["Sandeep"]

{'name': 'Sandeep', 'SID': 96674, 'Course': 'B.Tech'}

In [149]:
for person in record:
    print(record[person])

{'name': 'Sandeep', 'SID': 96674, 'Course': 'B.Tech'}
{'name': 'Pandey', 'SID': 90765, 'Course': 'B.Tech'}
{'name': 'Vivek', 'SID': 100365, 'Course': 'B.Tech'}
{'name': 'Shyam', 'SID': 99695, 'Course': 'B.Tech'}
{'name': 'Ujjawal', 'SID': 100087, 'Course': 'B.Tech'}
{'name': 'Rahul', 'SID': 90163, 'Course': 'B.Tech'}
{'name': 'Anuj', 'SID': 90161, 'Course': 'B.Tech'}


In [150]:
__name__

'__main__'

In [151]:
def calculate_area(base,height):
    return 1/2*(base*height)


if __name__=="__main__":
    a=calculate_area(10,20)
    print('area:',a)

area: 100.0


In [152]:
#raised error
1/0

ZeroDivisionError: division by zero

In [153]:
#reaised a type error
num1=input("Enter First number")
num2=input("Enter Second Number")
num1/num2

Enter First number54
Enter Second Number5


TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [154]:
class Human:
    def __init__(self,name):
        self.name=name
    def do_work(self):
        if self.name=="Sandeep":
            print(self.name,"Student")
        else:
            print("Other Occupation")

In [155]:
sandy=Human("Sandeep")

In [156]:
sandy.do_work()

Sandeep Student


In [157]:
sandy.name

'Sandeep'

In [158]:
vivek=Human("Vivek")

In [159]:
vivek.do_work()

Other Occupation


In [160]:
vivek.name

'Vivek'

In [161]:
a=[1,2,2,3,435,6,67,7,6,231,234]

In [162]:
a

[1, 2, 2, 3, 435, 6, 67, 7, 6, 231, 234]

In [163]:
for i in a:
    print(i)

1
2
2
3
435
6
67
7
6
231
234


In [164]:
a.sort()

In [165]:
dir(a)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [166]:
itr=iter(a)

In [167]:
itr

In [168]:
next(itr)

1

In [169]:
next(itr)

2

In [170]:
itr2=reversed(a)

In [171]:
itr2

In [172]:
next(itr2)

435

In [173]:
next(itr2)

234

In [174]:
dir('yield')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [175]:
def fib():
    a,b=0,1
    while True:
        yield a
        a,b=b,a+b
for f in fib():
    if f>100:
        break
    print(f)

0
1
1
2
3
5
8
13
21
34
55
89


In [176]:
num=[1,2,34,54,5,35,631,3,43,121,13,414,31,1]

In [177]:
even=[]
for i in num:
    if i%2==0:
        even.append(i)

In [178]:
even

[2, 34, 54, 414]

In [179]:
#Comprehensive
even2=[i for i in num if i%2==0]

In [180]:
even2

[2, 34, 54, 414]

In [181]:
odd=[i for i in num if i%2 !=0]

In [182]:
odd

[1, 5, 35, 631, 3, 43, 121, 13, 31, 1]

In [183]:
sqr=[i*i for i in num]

In [184]:
sqr

[1, 4, 1156, 2916, 25, 1225, 398161, 9, 1849, 14641, 169, 171396, 961, 1]

In [185]:
s=set([1,2,3,4,5,6,2,5])

In [186]:
s

{1, 2, 3, 4, 5, 6}

In [187]:
ev={i for i in s if i%2==0}

In [188]:
ev

{2, 4, 6}

In [189]:
cities=['Mumbai','New York','Paris','Kolambo']
countries=['India','USA','France','Sri Lanka']

In [190]:
z=zip(cities,countries)

In [191]:
z

In [192]:
for i in z:
    print(i)

('Mumbai', 'India')
('New York', 'USA')
('Paris', 'France')
('Kolambo', 'Sri Lanka')


In [193]:
d={city:country for city,country in zip(cities,countries)}

In [194]:
d

{'Mumbai': 'India',
 'New York': 'USA',
 'Paris': 'France',
 'Kolambo': 'Sri Lanka'}

In [195]:
d={country:city for city,country in zip(cities,countries)}

In [196]:
d

{'India': 'Mumbai',
 'USA': 'New York',
 'France': 'Paris',
 'Sri Lanka': 'Kolambo'}

In [197]:
a={}

In [198]:
type(a)

dict

In [199]:
b={"Sandeep"}

In [200]:
type(b)

set

In [201]:
c={"Name":"Sandeep"}

In [202]:
type(c)

dict

In [203]:
!pip install pytest

In [204]:
import numpy as np

In [205]:
a=np.array([12,23,324,235,135,15,16])

In [206]:
a

array([ 12,  23, 324, 235, 135,  15,  16])

In [207]:
type(a)

numpy.ndarray

In [208]:
import time
import sys

In [209]:
l=range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [210]:
array=np.arange(1000)
print(array.size*array.itemsize)

4000


In [211]:
size=10000000

In [212]:
l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("Time taken by the list",(time.time()-start)*1000)


start=time.time()
result=a1+a2
print("Time taken by Numpy",(time.time()-start)*1000)

Time taken by the list 1300.2407550811768
Time taken by Numpy 166.7625904083252


In [213]:
arr=np.array([1,2,3,4,5,5])

In [214]:
arr

array([1, 2, 3, 4, 5, 5])

In [215]:
arr.all()

True

In [216]:
arr.ndim

1

In [217]:
arr=np.array([[1,2,3],[1,134,53],[135,13,62]])

In [218]:
arr

array([[  1,   2,   3],
       [  1, 134,  53],
       [135,  13,  62]])

In [219]:
arr.ndim

2

In [220]:
arr.itemsize

4

In [221]:
a.dtype

dtype('int32')

In [222]:
arr2=np.array([[1,2,3],[1,134,53],[135,13,62]],dtype=float)

In [223]:
arr2

array([[  1.,   2.,   3.],
       [  1., 134.,  53.],
       [135.,  13.,  62.]])

In [224]:
arr2.dtype

dtype('float64')

In [225]:
arr2.size

9

In [226]:
arr.shape

(3, 3)

In [227]:
num=np.linspace(1,5,20)

In [228]:
num

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [229]:
num.ndim

1

In [230]:
num.reshape(4,5)

array([[1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526],
       [2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684],
       [3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842],
       [4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [231]:
num.reshape(5,4)

array([[1.        , 1.21052632, 1.42105263, 1.63157895],
       [1.84210526, 2.05263158, 2.26315789, 2.47368421],
       [2.68421053, 2.89473684, 3.10526316, 3.31578947],
       [3.52631579, 3.73684211, 3.94736842, 4.15789474],
       [4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [232]:
num.reshape(20,1)

array([[1.        ],
       [1.21052632],
       [1.42105263],
       [1.63157895],
       [1.84210526],
       [2.05263158],
       [2.26315789],
       [2.47368421],
       [2.68421053],
       [2.89473684],
       [3.10526316],
       [3.31578947],
       [3.52631579],
       [3.73684211],
       [3.94736842],
       [4.15789474],
       [4.36842105],
       [4.57894737],
       [4.78947368],
       [5.        ]])

In [233]:
num.reshape(2,10)

array([[1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684],
       [3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [234]:
num.ravel()

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [235]:
num.max()

5.0

In [236]:
num.sum(axis=0)

60.00000000000001

In [237]:
num.reshape(2,5,2)

array([[[1.        , 1.21052632],
        [1.42105263, 1.63157895],
        [1.84210526, 2.05263158],
        [2.26315789, 2.47368421],
        [2.68421053, 2.89473684]],

       [[3.10526316, 3.31578947],
        [3.52631579, 3.73684211],
        [3.94736842, 4.15789474],
        [4.36842105, 4.57894737],
        [4.78947368, 5.        ]]])

In [238]:
size=100000000

l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

#Time analysis for normal list
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("Time taken by the list",(time.time()-start)*1000)

#time analysis for Numpy
start=time.time()
result=a1+a2
print("Time taken by Numpy",(time.time()-start)*1000)

Time taken by the list 13476.357221603394
Time taken by Numpy 1373.3258247375488


In [239]:
new=np.arange(30)

In [240]:
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [241]:
np.hsplit(new,5)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23]),
 array([24, 25, 26, 27, 28, 29])]

In [242]:
new.ndim

1

In [243]:
new.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [244]:
s=np.arange(10).reshape(2,5)

In [245]:
s

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [246]:
k= s>5 
k

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [247]:
s[k]

array([6, 7, 8, 9])

In [248]:
a=np.array([1,2,3,4],dtype=int)
b=np.array([2,4,6,8],dtype=float)
a*b

array([ 2.,  8., 18., 32.])

In [249]:
b.nbytes

32

In [250]:
c=np.arange(1,15).reshape(2,7)

In [251]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [252]:
c[1,5]

13

In [253]:
c[1,-2]

13

In [254]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [255]:
c[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [256]:
c[:,1]

array([2, 9])

In [257]:
c[0,1:6:2]

array([2, 4, 6])

In [258]:
c[1,3]=25

In [259]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 25, 12, 13, 14]])

In [260]:
z=np.zeros((2,3,3,4))

In [261]:
z

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [262]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [263]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [264]:
np.full((2,3),10,dtype=float)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [265]:
z.ndim

4

In [266]:
np.full((2,3),"Matrix")

array([['Matrix', 'Matrix', 'Matrix'],
       ['Matrix', 'Matrix', 'Matrix']], dtype='<U6')

In [273]:
import random
np.random.rand(1,3,4)

array([[[0.35115857, 0.68142042, 0.71299101, 0.44412398],
        [0.1735684 , 0.94360395, 0.07545769, 0.09031565],
        [0.63622996, 0.89113914, 0.63062774, 0.6164695 ]]])

In [274]:
import random
np.random.rand(1,3,4).reshape(2,6)

array([[0.0236748 , 0.4296356 , 0.45172747, 0.26757796, 0.62802059,
        0.48832159],
       [0.15252073, 0.32621845, 0.32653211, 0.53871219, 0.85936151,
        0.39649181]])

In [275]:
np.random.rand(4,3)

array([[0.43807905, 0.20213793, 0.37125291],
       [0.82106162, 0.89236323, 0.33244889],
       [0.92967258, 0.96721899, 0.66651481],
       [0.68031734, 0.12931594, 0.62418926]])

In [276]:
np.random.randint(7,size=(3,4))

array([[5, 5, 2, 4],
       [3, 3, 2, 6],
       [4, 3, 0, 0]])

In [277]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [280]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [295]:
output=np.ones((5,5),dtype=int)
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [298]:
z=np.zeros((3,3),dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [299]:
z[1,1]=9

In [300]:
z

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [301]:
output[1:4,1:4]=z

In [302]:
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [305]:
a=np.array([1,2,3])
b=a
b[1]=56
print(a)
b

[ 1 56  3]


array([ 1, 56,  3])

In [306]:
a=np.array([1,2,3])
b=a.copy()
b[1]=56
print(a)
b

[1 2 3]


array([ 1, 56,  3])

In [307]:
a

array([1, 2, 3])

In [6]:
a=np.array([1,2,3,4])

In [7]:
a**2

array([ 1,  4,  9, 16])

In [8]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [9]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [13]:
#Linear Algebra
import random

m1=random.randint(1,4)

In [14]:
m1

4

In [15]:
c=np.identity(3)

In [16]:
np.linalg.det(c)

1.0

In [20]:
m2=np.array([[1,2,3],[4,5,6]])
np.min(m2)

1

In [24]:
np.sum((a),axis=0)

10

In [25]:
np.genfromtxt('book.txt')

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [27]:
#index with a list in Numpy
m3=np.array([1,2,3,4,5,6,7,8,9])

In [28]:
m3[[2,5,7]]

array([3, 6, 8])

In [29]:
m3[m3>5]

array([6, 7, 8, 9])

In [31]:
np.any(m3>4,axis=0)

True

In [34]:
~(True)

-2

In [36]:
m4=np.arange(1,31).reshape(6,5)

In [37]:
m4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
m4[2,0:2]

array([11, 12])

In [40]:
m4[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [41]:
m4[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [46]:
for i in m4:
    if np.any(i<6):
        if
        print(m4[i+1])
        i=i+1
    else:
        break

IndexError: index 6 is out of bounds for axis 0 with size 6

In [19]:
a=2
b=a
b

2

In [20]:
id(a)

2035751479632

In [21]:
id(b)

2035751479632

In [17]:
b=7

In [18]:
a

2

In [12]:
a=b

In [13]:
a

4

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head(7)

User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000001  P00069042      F   0-17          10             A   
1  1000001  P00248942      F   0-17          10             A   
2  1000001  P00087842      F   0-17          10             A   
3  1000001  P00085442      F   0-17          10             A   
4  1000002  P00285442      M    55+          16             C   
5  1000003  P00193542      M  26-35          15             A   
6  1000004  P00184942      M  46-50           7             B   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   
5                          3               0                   1   
6                          2               1                   1   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969  
5                 2.0                 NaN     15227  
6                 8.0                17.0     19215

In [4]:
df.isnull()

User_ID  Product_ID  Gender    Age  Occupation  City_Category  \
0         False       False   False  False       False          False   
1         False       False   False  False       False          False   
2         False       False   False  False       False          False   
3         False       False   False  False       False          False   
4         False       False   False  False       False          False   
...         ...         ...     ...    ...         ...            ...   
550063    False       False   False  False       False          False   
550064    False       False   False  False       False          False   
550065    False       False   False  False       False          False   
550066    False       False   False  False       False          False   
550067    False       False   False  False       False          False   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                            False           False               False   
1                            False           False               False   
2                            False           False               False   
3                            False           False               False   
4                            False           False               False   
...                            ...             ...                 ...   
550063                       False           False               False   
550064                       False           False               False   
550065                       False           False               False   
550066                       False           False               False   
550067                       False           False               False   

        Product_Category_2  Product_Category_3  Purchase  
0                     True                True     False  
1                    False               False     False  
2                     True                True     False  
3                    False                True     False  
4                     True                True     False  
...                    ...                 ...       ...  
550063                True                True     False  
550064                True                True     False  
550065                True                True     False  
550066                True                True     False  
550067                True                True     False  

[550068 rows x 12 columns]

In [5]:
df.tail()

User_ID Product_ID Gender    Age  Occupation City_Category  \
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490

In [6]:
df.shape

(550068, 12)

In [7]:
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [9]:
df.nunique()

User_ID                        5891
Product_ID                     3631
Gender                            2
Age                               7
Occupation                       21
City_Category                     3
Stay_In_Current_City_Years        5
Marital_Status                    2
Product_Category_1               20
Product_Category_2               17
Product_Category_3               15
Purchase                      18105
dtype: int64